# Generated by Django 5.1.7 on 2026-03-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Location / स्थान')),
                ('soil_type', models.CharField(choices=[('loamy', 'Loamy / दोमट'), ('sandy', 'Sandy / बलुई'), ('clay', 'Clay / चिकनी मिट्टी'), ('silt', 'Silty / गाद मिट्टी'), ('black', 'Black Cotton / काली मिट्टी'), ('red', 'Red / लाल मिट्टी'), ('alluvial', 'Alluvial / जलोढ़ मिट्टी')], max_length=50, verbose_name='Soil Type / मिट्टी का प्रकार')),
                ('season', models.CharField(choices=[('kharif', 'Kharif (Jun-Nov) / खरीफ'), ('rabi', 'Rabi (Nov-Apr) / रबी'), ('zaid', 'Zaid (Apr-Jun) / जायद'), ('year_round', 'Year Round / साल भर')], max_length=50, verbose_name='Season / ऋतु')),
                ('water_availability', models.CharField(choices=[('irrigated', 'Well Irrigated / सिंचित'), ('semi_irrigated', 'Semi Irrigated / अर्ध-सिंचित'), ('rainfed', 'Rain-fed Only / वर्षा आधारित'), ('drip', 'Drip Irrigation / ड्रिप सिंचाई')], max_length=50, verbose_name='Water Availability / जल उपलब्धता')),
                ('land_area', models.FloatField(default=1.0, verbose_name='Land Area (acres) / भूमि क्षेत्र (एकड़)')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी (Hindi)')], default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weather_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Farmer Query',
                'verbose_name_plural': 'Farmer Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_response_raw', models.TextField(blank=True)),
                ('crops_data', models.JSONField(default=list)),
                ('mandi_prices_data', models.JSONField(default=list)),
                ('calendar_data', models.JSONField(default=list)),
                ('farming_tips', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='core.farmerquery')),
            ],
            options={
                'verbose_name': 'Crop Recommendation',
            },
        ),
    ]
