# Generated by Django 5.2.13 on 2026-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farmerquery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='croprecommendation',
            name='government_schemes_data',
            field=models.JSONField(default=list),
        ),
    ]
